const resList = [
    {
        type: "restaurant",
        data: {
          type: "F",
          id: "193210",
          name: "Chopstick",
          uuid: "259b62fa-9764-4c6f-b915-0988773dc3e4",
          city: "1",
          area: "Btm Layout",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "h7h8vt4y5cur3plpkf1x",
          cuisines: [
            "Chinese",
            "Thai",
            "Seafood",
            "Asian",
            "Combo",
            "Healthy Food",
            "Beverages",
          ],
          tags: [],
          costForTwo: 35000,
          costForTwoString: "₹350 FOR TWO",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          slaString: "22 MINS",
          lastMileTravel: 3,
          slugs: {
            restaurant: "the-chopstick-btm-btm",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "No. 805/A, 16th Mai, 7th Cross , Next to Pizza Hut, Stage 2, BTM Layout, Bangalore, Karnataka",
          locality: "2nd Stage",
          parentId: 1783,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [{ type: "PROMOTED" }],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5717644~p=1~eid=00000186-09ee-32fc-2d93-8c6c001a010a",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "3 kms",
          hasSurge: false,
          sla: {
            restaurantId: "193210",
            deliveryTime: 22,
            minDeliveryTime: 22,
            maxDeliveryTime: 22,
            lastMileTravel: 3,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.0",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
          type: "F",
          id: "70161",
          name: "Imperio Restaurant",
          uuid: "579609b6-73f2-4d8f-a777-20929a10b7b3",
          city: "1",
          area: "Hrbr Layout",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "uz8axstizmuiij9adupe",
          cuisines: [
            "Chinese",
            "South Indian",
            "North Indian",
            "Continental",
            "Desserts",
            "Kerala",
            "Andhra",
            "Beverages",
            "Mughlai",
            "Seafood",
            "Hyderabadi",
            "Pan-Asian",
            "Thai",
          ],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 35,
          minDeliveryTime: 30,
          maxDeliveryTime: 40,
          slaString: "30-40 MINS",
          lastMileTravel: 12.300000190734863,
          slugs: {
            restaurant:
              "imperio-restaurant-kalyan-nagar-kammanahallikalyan-nagar",
            city: "bangalore",
          },
          cityState: "1",
          address: "No.429 1st block hrbr layout kalyan Nagar",
          locality: "1st Block",
          parentId: 5610,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "Closes soon",
          },
          longDistanceEnabled: 1,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "12.3 kms",
          hasSurge: false,
          sla: {
            restaurantId: "70161",
            deliveryTime: 35,
            minDeliveryTime: 30,
            maxDeliveryTime: 40,
            lastMileTravel: 12.300000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "IT_IS_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
          type: "F",
          id: "588705",
          name: "La Pino'z Pizza",
          uuid: "a421884c-e814-4349-aff7-7bb734ce5549",
          city: "1",
          area: "JP Nagar",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "w6roonblq3fa5wrtlgys",
          cuisines: [
            "Italian",
            "Pizzas",
            "Mexican",
            "Desserts",
            "Beverages",
          ],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          slaString: "31 MINS",
          lastMileTravel: 6.400000095367432,
          slugs: {
            restaurant: "la-pino'z-pizza-jp-nagar-jp-nagar",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "#309,1ST FLOOR,100 FEET RING ROAD,NEAR DELMIACIRCLE,J P NAGAR,5TH PHASE,BANGALORE, BTM Layout , B.B.M.P South, Karnataka-560078",
          locality: "5TH Phase",
          parentId: 4961,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.4 kms",
          hasSurge: false,
          sla: {
            restaurantId: "588705",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            lastMileTravel: 6.400000095367432,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.9",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
          type: "F",
          id: "217048",
          name: "Chinese BAE",
          uuid: "f053c092-04d2-4551-b081-4449cf1a559f",
          city: "1",
          area: "BTM Layout",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "n2lfnd2v4jf4x6l7rnos",
          cuisines: [
            "Chinese",
            "Thai",
            "Seafood",
            "Asian",
            "Combo",
            "Healthy Food",
            "Beverages",
          ],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          slaString: "24 MINS",
          lastMileTravel: 3,
          slugs: {
            restaurant: "chinese-bae-btm-btm",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "NO.805/A, 1ST FLOOR, 7TH CROSS, BTM LAYOUT 2ND STAGE, MICO LAYOUT, BANGALORE., B.B.M.P South (Karnataka) - 560076",
          locality: "2nd Stage",
          parentId: 9769,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [{ type: "PROMOTED" }],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5717643~p=4~eid=00000186-09ee-32fc-2d93-8c6d001a041a",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "3 kms",
          hasSurge: false,
          sla: {
            restaurantId: "217048",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            lastMileTravel: 3,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.1",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
          type: "F",
          id: "418",
          name: "Ande Ka Funda",
          uuid: "80f87c90-b6f4-48ef-b110-9bbfad549b39",
          city: "1",
          area: "Kadubeesanahalli",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "hwnvirxf8oxaubiflcag",
          cuisines: ["North Indian"],
          tags: [],
          costForTwo: 10000,
          costForTwoString: "₹100 FOR TWO",
          deliveryTime: 39,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          slaString: "35-45 MINS",
          lastMileTravel: 11,
          slugs: {
            restaurant:
              "ande-ka-funda-shymala-reddy-dental-college-road-marathahalli",
            city: "bangalore",
          },
          cityState: "1",
          address: "6, Shymala Reddy Dental College Road, Marathahalli",
          locality: "Munnekolala",
          parentId: 15677,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 1,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "11 kms",
          hasSurge: false,
          sla: {
            restaurantId: "418",
            deliveryTime: 39,
            minDeliveryTime: 35,
            maxDeliveryTime: 45,
            lastMileTravel: 11,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "IT_IS_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.5",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
          type: "F",
          id: "337335",
          name: "Kannur food kitchen",
          uuid: "c70b61bc-0f68-4e24-996b-749fbf295c35",
          city: "1",
          area: "BTM Layout",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "a27weqanhnszqiuzsoik",
          cuisines: ["Kerala", "Biryani", "Beverages"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          slaString: "19 MINS",
          lastMileTravel: 2.9000000953674316,
          slugs: {
            restaurant: "kannur-food-kitchen-btm-btm",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "kannur food point, Chocolate Factory Road, Tavarekere, Cashier Layout, 1st Stage, BTM Layout, thavrakharea, Karnataka, India",
          locality: "1st  Stage",
          parentId: 114756,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Free Delivery",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "Closes soon",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2.9 kms",
          hasSurge: false,
          sla: {
            restaurantId: "337335",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            lastMileTravel: 2.9000000953674316,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.8",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
          type: "F",
          id: "203015",
          name: "Shapana dhaba",
          uuid: "3e69b27f-104b-400d-b238-494ebf8e4688",
          city: "1",
          area: "Btm Layout",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "dlx42acjc2yqzajz714i",
          cuisines: ["Chinese", "North Indian", "Biryani"],
          tags: [],
          costForTwo: 15000,
          costForTwoString: "₹150 FOR TWO",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          slaString: "33 MINS",
          lastMileTravel: 4,
          slugs: {
            restaurant: "shapana-dhaba-btm-btm",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "H.NO 267, 26 main, 7th cross road 26th main EWS Layout",
          locality: "EWS Layout",
          parentId: 181928,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "70% off",
            shortDescriptionList: [
              {
                meta: "70% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "70% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "70% OFF",
            shortDescriptionList: [
              {
                meta: "Free Delivery",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "70% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4 kms",
          hasSurge: false,
          sla: {
            restaurantId: "203015",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            lastMileTravel: 4,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.5",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
    }
]

export default resList;